global: 
  scrape_interval: 15s 
  evaluation_interval: 15s 
 
scrape_configs: 
  # Prometheus monitors itself 
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['localhost:9090'] 
    scrape_interval: 10s 
 
  # Future: Motor controller metrics (disabled for now) 
  # - job_name: 'motor-controller' 
  #   static_configs: 
  #     - targets: ['host.docker.internal:8767'] 
  #   scrape_interval: 5s 
